name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  CLAZY_CHECKS: "level1"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
        container:
          #- suse-qt512
          - suse-qt515
        pam:
          - ON
          - OFF
    runs-on: ubuntu-latest
    container:
      image: liridev/${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: |
          set -x
          zypper --non-interactive install python3-docutils
      - name: Build
        run: |
          set -x
          mkdir -p build
          cd build
          if [ "${{ matrix.compiler }}" == "clang" ]; then
            export CC=clang
            #export CXX=clang++
            export CXX=clazy
          fi
          cmake .. \
            -DBUILD_MAN_PAGES:BOOL=ON \
            -DENABLE_PAM:BOOL=${{ matrix.pam }} \
            -DLOGIN_DEFS_PATH:path="/usr/etc/login.defs"
          make -j $(getconf _NPROCESSORS_ONLN)
          sudo make install
