name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  CLAZY_CHECKS: "level1"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
        pam:
          - ON
          - OFF
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Dependencies
        run: |
          set -x
          sudo sed -i '/^#\sdeb-src /s/^#//' "/etc/apt/sources.list"
          sudo apt-get update -y
          DEBIAN_FRONTEND=noninteractive sudo apt-get build-dep sddm -y
          DEBIAN_FRONTEND=noninteractive sudo apt-get install clang clazy sudo -y
      - name: Build
        run: |
          set -x
          mkdir -p build
          cd build
          if [ "${{ matrix.compiler }}" == "clang" ]; then
            export CC=clang
            #export CXX=clang++
            export CXX=clazy
          fi
          cmake .. \
            -DBUILD_MAN_PAGES:BOOL=ON \
            -DENABLE_PAM:BOOL=${{ matrix.pam }}
          make -j $(getconf _NPROCESSORS_ONLN)
          sudo make install
